version: "3.7"
services:

  mongo:
    image: mongo
    hostname: mongodb
    container_name: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${DOCKER_CONFIGS}/mongo/mongod.conf:/etc/mongod.conf
      - ${DOCKER_CONFIGS}/mongo/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    command: ["-f", "/etc/mongod.conf"]

  mongoexpress:
    image: mongo-express
    container_name: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo

  mailhog:
    build: ${DOCKER_CONFIGS}/mailhog
    ports:
      - ${MAILHOG_PORT}:1025
      - ${MAILHOG_PORT_UI}:8025
