version: "3.8"

services:
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27037:27017

  mongoexpress:
    image: mongo-express:latest
    hostname: mongo-express
    links:
      - mongo:mongo
    ports:
      - 8081:8081
    restart: always
    mem_limit: 128m
    environment:
      - WEB_USER='user'
      - WEB_PASS='pass'
    command: sh -c 'sleep 10 && tini -- node app'
