version: "3.8"
services:

  mongo:
    image: mongo
    hostname: mongodb
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ${DOCKER_CONFIGS}/mongo/mongod.conf:/etc/mongod.conf
      - ${DOCKER_CONFIGS}/mongo/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
    command: ["-f", "/etc/mongod.conf"]

  mongo-ui:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - mongo

  redis:
    image: redis
    expose:
      - ${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:6379
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=development
    volumes:
      - ./redis_data:/data

  redis-ui:
    hostname: redis-ui
    image: rediscommander/redis-commander:latest
    ports:
      - ${REDIS_COMMANDER_PORT}:8081
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - HTTP_USER=${REDIS_COMMANDER_HTTP_USER}
      - HTTP_PASSWORD=${REDIS_COMMANDER_HTTP_PASSWORD}
    depends_on:
      - redis

  postgres:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql/data/

  postgres-ui:
    image: adminer
    ports:
      - ${POSTGRES_UI_PORT}:8080
    depends_on:
      - postgres

volumes:
  db-data:
